services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: SecretPassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./init-scripts:/docker-entrypoint-initdb.d
 
volumes:
  pgdata:
